spring:
  application:
    name: gulimall-auth-server
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/