spring:
  application:
    name: gulimall-seckill
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 25000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/