spring:
  cloud:
    gateway:
      routes:
      - id: gulimall_auth_route
        uri: lb://gulimall-auth-server
        predicates:
        - Host=auth.adjoined.me
      - id: gulimall_product_route
        uri: lb://gulimall-product
        predicates:
        - Host=product.adjoined.me
      - id: gulimall_cart_route
        uri: lb://gulimall-cart
        predicates:
          - Host=cart.adjoined.me
      - id: gulimall_order_route
        uri: lb://gulimall-order
        predicates:
          - Host=order.adjoined.me
      - id: gulimall_ware_route
        uri: lb://gulimall-ware
        predicates:
          - Host=ware.adjoined.me
      - id: gulimall_seckill_route
        uri: lb://gulimall-seckill
        predicates:
          - Host=seckill.adjoined.me



#- id: test_route
      ##        uri: lb://gulimall-product
      ##        predicates:
      ##        - Path=/api/product/**
      ##        filters:
      ##        - RewritePath=/api/(?<segment>.*),/$\{segment}
      ##      - id: qq_route
      ##        uri: https://www.qq.com
      ##        predicates:
      ##        - Query=url,qq

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/