spring:
  cloud:
    gateway:
      routes:
      - id: test_route
        uri: lb://gulimall-product
        predicates:
        - Path=/api/product/**
        filters:
        - RewritePath=/api/(?<segment>.*),/$\{segment}
      - id: qq_route
        uri: https://www.qq.com
        predicates:
        - Query=url,qq
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/