spring:
  cloud:
    gateway:
      routes:
      - id: gulimall_auth_route
        uri: lb://gulimall-auth-server
        predicates:
        - Host=auth.adjoined.me
      - id: gulimall_product_route
        uri: lb://gulimall-product
        predicates:
        - Host=product.adjoined.me

#- id: test_route
      ##        uri: lb://gulimall-product
      ##        predicates:
      ##        - Path=/api/product/**
      ##        filters:
      ##        - RewritePath=/api/(?<segment>.*),/$\{segment}
      ##      - id: qq_route
      ##        uri: https://www.qq.com
      ##        predicates:
      ##        - Query=url,qq

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/